### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by 0kuang** [wechaty/wechaty-puppet-xp#3]
When I try Ding-Dong Bot, Frida reports the follow error:

```shell
Error: Could not locate the bindings file. Tried:
 → D:\ding\node_modules\frida\build\frida_binding.node
 → D:\ding\node_modules\frida\build\Debug\frida_binding.node
 → D:\ding\node_modules\frida\build\Release\frida_binding.node
 → D:\ding\node_modules\frida\out\Debug\frida_binding.node
 → D:\ding\node_modules\frida\Debug\frida_binding.node
 → D:\ding\node_modules\frida\out\Release\frida_binding.node
 → D:\ding\node_modules\frida\Release\frida_binding.node
 → D:\ding\node_modules\frida\build\default\frida_binding.node
 → D:\ding\node_modules\frida\compiled\16.5.0\win32\x64\frida_binding.node
 → D:\ding\frida_binding.node
    at bindings (D:\ding\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (D:\ding\node_modules\frida\dist\native.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\node_modules\frida\dist\cancellable.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\node_modules\frida\dist\index.js:5:27)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\node_modules\frida-sidecar\src\frida.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\node_modules\frida-sidecar\src\sidecar-body\sidecar-body.ts:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\node_modules\frida-sidecar\src\sidecar-body\mod.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\node_modules\frida-sidecar\src\mod.ts:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\node_modules\wechaty-puppet-xp\src\puppet-xp.ts:57:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\node_modules\wechaty-puppet-xp\src\mod.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\ding\ding.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Module.m._compile (D:\Scoop\persist\nvm\nodejs\v16.5.0\node_modules\ts-node\src\index.ts:1225:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Scoop\persist\nvm\nodejs\v16.5.0\node_modules\ts-node\src\index.ts:1228:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at main (D:\Scoop\persist\nvm\nodejs\v16.5.0\node_modules\ts-node\src\bin.ts:330:12)
    at Object.<anonymous> (D:\Scoop\persist\nvm\nodejs\v16.5.0\node_modules\ts-node\src\bin.ts:477:3)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```
This is my typescript code `ding.ts`:
```typescript
import { log, Wechaty } from 'wechaty'
import { EventLogger, QRCodeTerminal, DingDong } from "wechaty-plugin-contrib"
import { PuppetXp } from "wechaty-puppet-xp"
// import { PuppetWeChat } from "wechaty-puppet-wechat"

const puppet = new PuppetXp()
// const puppet = new PuppetWeChat()
const bot = new Wechaty({
    name: 'Clock In Helper',
    puppet
})

// bind event listener
// bot.on('scan', onScan)

// use plugins
bot.use(QRCodeTerminal({ small: true }))
bot.use(EventLogger())
bot.use(DingDong())

bot.start()
    .then(() => log.info("DingDong", "Started."))
    .catch(e => log.error("DingDong", e))
```
The following is my environment configuration.
```shell
$ npm list
ding@ D:\ding
+-- axios@0.21.1
+-- frida@15.0.10
+-- node-schedule@2.0.0
+-- wechaty-plugin-contrib@0.14.23
+-- wechaty-puppet-wechat@0.28.3
+-- wechaty-puppet-xp@0.2.6
`-- wechaty@0.62.3

$ npm list -g
D:\Scoop\apps\nvm\current\nodejs\nodejs -> .\
+-- @swc/core@1.2.66
+-- @swc/wasm@1.2.66
+-- @types/node@16.4.7
+-- cross-env@7.0.3
+-- npm@7.19.1
+-- nrm@1.2.1
+-- ts-node@10.1.0
`-- typescript@4.3.5
```
My node version is v16.5.0 & npm version is 7.19.1.
```shell
$ npm -v
7.19.1

$ node --version
v16.5.0
```

I have install the `Wechat for Windows v3.3.0.115` with the default installation options, but I don't know if some additional operations are needed for Frida to hook wechat.

And my OS version is:
```text
版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎7/‎13
操作系统版本	22000.100
体验	Windows Feature Experience Pack 421.18901.0.3
```

**I hope this information can locate the problem. If you need any more information, please reply to me.**

**Comment by Randolph603** [comment]
Try the same code but get different error:
**Not sure why unable to find method 'init'**

22:38:19 ERR SidecarBody [SCRIPT_MESSAGRE_HANDLER_SYMBOL]() MessageType.Error: Error: access violation accessing 0x61899728
    at <anonymous> (frida/runtime/core.js:127)
    at <eval> (/script1.js:199)
[Error: unable to find method 'init'] { name: undefined }
22:38:19 ERR Wechaty start() exception: unable to find method 'init'
22:38:19 INFO WechatyPluginContrib EventLogger error: Error: unable to find method 'init'
22:38:19 INFO DingDong Started.
Error: Error: access violation accessing 0x61899728
    at WeChatSidecar.SidecarBody.<computed> (C:\Users\cliu6\Documents\cloud-bot\node_modules\wechaty-puppet-xp\node_modules\frida-sidecar\src\sidecar-body\sidecar-body.ts:394:21) 
    at C:\Users\cliu6\Documents\cloud-bot\node_modules\frida\dist\script.js:95:21

**Comment by huan** [comment]
Please refer to https://github.com/wechaty/wechaty-puppet-xp#1-error-could-not-locate-the-binding-file-tried-node_modulesfridabuildfrida_bindingnode

**Comment by huan** [comment]
The latest version (v0.3.6 or above) of XP should be able to recover from this situation and install everything automatically if it deletes there's anything that needs to be fixed.

Related to: https://github.com/huan/sidecar/issues/14

@0kuang please retry and let me know if it works for you or not, thank you very much.

**Comment by huan** [comment]
kindly ping @0kuang

**Comment by 0kuang** [comment]
> kindly ping @0kuang

Thanks, I have solved this problem by re-install frida with an unblocked network connection.

Now, DingDong bot can run successfully.

Hope you can improve other features as soon as possible and I am happy to migrate my project to `wechaty-puppet-xp` after that.

Feature requirements:
1. get room by room name,
2. mention room members by their alias.

Finally, thank you again for your help.

**Comment by huan** [comment]
Glad to know that your have run XP successfully, congratulations!

Could you please help us to try to install the latest version of XP under your blocked network connection again to see if it can works now? Because we have some workaround added and want to know if it solves the problem.

Thank you very much.

**Comment by 0kuang** [comment]
I successfully installed `wechaty-puppet-xp@0.3.21` from [npm source](https://registry.npmjs.org/) under the blocked network connection. But when I use taobao mirrors([taobao registry](https://registry.npm.taobao.org/)), I still encounter this problem.

P.S. I used taobao mirros when I filed the issue. I am not sure whether this problem is due to taobao mirros.

**Comment by huan** [comment]
@0kuang Thank you very much for the feedback!

**Comment by atorber** [comment]
> 1. get room by room name

**Comment by atorber** [comment]
@0kuang 'get room by room name' have support in version 0.3.23 ，you can try it now.
 And 'mention room members by their alias ' is under development, please wait a moment.
Thank you for your attention！
