### ISSUE TITLE
Try example/ding-dong-bot.ts and get process not found error

### ISSUE THREAD

**Issue by Randolph603** [wechaty/wechaty-puppet-xp#4]
Puppet Version: 0.3.3

Please wait... I'm trying to login in...

Bot start() fail: Error: Process not found
    at Device.getProcess (E:\Projects\wechaty-puppet-xp\node_modules\frida\dist\device.js:66:19)
    at Device.getPid (E:\Projects\wechaty-puppet-xp\node_modules\frida\dist\device.js:138:25)
    at Device.attach (E:\Projects\wechaty-puppet-xp\node_modules\frida\dist\device.js:120:21)
    at Object.attach (E:\Projects\wechaty-puppet-xp\node_modules\frida\dist\index.js:60:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! wechaty-puppet-xp@0.3.3 start: `ts-node examples/ding-dong-bot.ts`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the wechaty-puppet-xp@0.3.3 start script.

**Comment by Randolph603** [comment]
Solved by running wechat client
